version: "3"

services:
  app:
    container_name: ChatGPT-Line-Bot
    build: .
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      default:
        ipv4_address: 192.168.128.1
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.128.0/24